import PdfPrinterModule from "pdfmake/js/Printer.js";
import type { TDocumentDefinitions } from "pdfmake/interfaces.js";

// pdfmake uses CJS exports.default — ESM import wraps it in { default: ... }
const PdfPrinter = (PdfPrinterModule as { default?: typeof PdfPrinterModule }).default ?? PdfPrinterModule;

export function generateCSV(
  headers: string[],
  rows: Record<string, string | number>[],
): Buffer {
  const BOM = "\uFEFF";
  const lines: string[] = [headers.join(";")];
  for (const row of rows) {
    lines.push(headers.map((h) => String(row[h] ?? "")).join(";"));
  }
  return Buffer.from(BOM + lines.join("\n"), "utf-8");
}

export async function generatePDF(
  title: string,
  headers: string[],
  rows: Record<string, string | number>[],
): Promise<Buffer> {
  const fonts = {
    Helvetica: {
      normal: "Helvetica",
      bold: "Helvetica-Bold",
      italics: "Helvetica-Oblique",
      bolditalics: "Helvetica-BoldOblique",
    },
  };

  const printer = new PdfPrinter(fonts);

  const tableBody = [
    headers.map((h) => ({ text: h, bold: true })),
    ...rows.map((row) => headers.map((h) => String(row[h] ?? ""))),
  ];

  const docDefinition: TDocumentDefinitions = {
    defaultStyle: { font: "Helvetica" },
    content: [
      { text: title, style: "header" },
      {
        table: {
          headerRows: 1,
          widths: headers.map(() => "*"),
          body: tableBody,
        },
        layout: "lightHorizontalLines",
      },
    ],
    styles: {
      header: { fontSize: 16, bold: true, margin: [0, 0, 0, 10] },
    },
    footer: {
      text: `Generated by OpenKick - ${new Date().toISOString().split("T")[0]}. Anonymised export.`,
      alignment: "center" as const,
      fontSize: 8,
      margin: [0, 10, 0, 0],
    },
  };

  const pdfDoc = await printer.createPdfKitDocument(docDefinition);

  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    pdfDoc.on("data", (chunk: Buffer) => chunks.push(chunk));
    pdfDoc.on("end", () => resolve(Buffer.concat(chunks)));
    pdfDoc.on("error", reject);
    pdfDoc.end();
  });
}
