#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────
# OpenKick — Interactive Deployment Script for cyon.ch
# ─────────────────────────────────────────────────
# Builds the project locally and deploys via rsync/scp
# to a cyon.ch shared hosting account.
# ─────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$PROJECT_DIR/.deploy-cyon.conf"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║   OpenKick — Deploy to cyon.ch               ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ─── Load previous config (non-secret values) ────

PREV_SSH_USER="" PREV_SSH_HOST="" PREV_REMOTE_PATH="" PREV_SITE_URL=""
PREV_NODE_PORT="" PREV_WAHA_URL="" PREV_WAHA_PORT="" PREV_WEBHOOK_URL=""
PREV_SMTP_HOST="" PREV_SMTP_PORT="" PREV_SMTP_USER="" PREV_CORS_ORIGIN=""

if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$CONFIG_FILE"
  echo "  ℹ  Loaded previous config from .deploy-cyon.conf"
  echo "     Press Enter to keep the shown default."
  echo ""
fi

# Helper: prompt with a default value
prompt_with_default() {
  local prompt_text="$1" default_val="$2" var_name="$3"
  if [[ -n "$default_val" ]]; then
    read -rp "${prompt_text} [${default_val}]: " input
    eval "$var_name=\"\${input:-$default_val}\""
  else
    read -rp "${prompt_text}: " input
    eval "$var_name=\"\$input\""
  fi
}

# ─── Collect all values upfront ───────────────────

prompt_with_default "SSH user (e.g. salach)" "$PREV_SSH_USER" SSH_USER
prompt_with_default "SSH host (e.g. salach.cyon.ch or s056.cyon.net)" "$PREV_SSH_HOST" SSH_HOST
prompt_with_default "Remote web root path (e.g. /home/salach/public_html/fluegelflitzer)" "$PREV_REMOTE_PATH" REMOTE_PATH
prompt_with_default "Subdomain URL (e.g. https://fluegelflitzer.sala.ch)" "$PREV_SITE_URL" SITE_URL
prompt_with_default "Node.js port on cyon (e.g. 40001 — pick an unused high port)" "$PREV_NODE_PORT" NODE_PORT
read -rp "JWT secret for production: " JWT_SECRET
echo ""

# Optional: WAHA / WhatsApp config
prompt_with_default "WAHA URL (leave empty to skip WhatsApp)" "$PREV_WAHA_URL" WAHA_URL
WAHA_PORT=""
WEBHOOK_URL=""
if [[ -n "$WAHA_URL" ]]; then
  prompt_with_default "WAHA port" "$PREV_WAHA_PORT" WAHA_PORT
  local_default_webhook="${SITE_URL}/api/whatsapp/webhook"
  prompt_with_default "Webhook URL for WAHA" "${PREV_WEBHOOK_URL:-$local_default_webhook}" WEBHOOK_URL
fi

# Optional: LLM / Email
read -rp "OpenAI API key (leave empty to skip): " OPENAI_API_KEY
prompt_with_default "SMTP host for email (leave empty to skip)" "$PREV_SMTP_HOST" SMTP_HOST
SMTP_PORT=""
SMTP_USER=""
SMTP_PASS=""
if [[ -n "$SMTP_HOST" ]]; then
  prompt_with_default "SMTP port (e.g. 587)" "$PREV_SMTP_PORT" SMTP_PORT
  prompt_with_default "SMTP user" "$PREV_SMTP_USER" SMTP_USER
  read -rsp "SMTP password: " SMTP_PASS
  echo ""
fi

prompt_with_default "CORS origin" "${PREV_CORS_ORIGIN:-$SITE_URL}" CORS_ORIGIN
CORS_ORIGIN="${CORS_ORIGIN:-$SITE_URL}"

# ─── Save non-secret values for next run ──────────

cat > "$CONFIG_FILE" <<CONFEOF
# Auto-generated by deploy-cyon.sh — non-secret values only
PREV_SSH_USER="${SSH_USER}"
PREV_SSH_HOST="${SSH_HOST}"
PREV_REMOTE_PATH="${REMOTE_PATH}"
PREV_SITE_URL="${SITE_URL}"
PREV_NODE_PORT="${NODE_PORT}"
PREV_WAHA_URL="${WAHA_URL}"
PREV_WAHA_PORT="${WAHA_PORT}"
PREV_WEBHOOK_URL="${WEBHOOK_URL}"
PREV_SMTP_HOST="${SMTP_HOST}"
PREV_SMTP_PORT="${SMTP_PORT}"
PREV_SMTP_USER="${SMTP_USER}"
PREV_CORS_ORIGIN="${CORS_ORIGIN}"
CONFEOF

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  SSH:        ${SSH_USER}@${SSH_HOST}"
echo "  Remote:     ${REMOTE_PATH}"
echo "  Site URL:   ${SITE_URL}"
echo "  Node port:  ${NODE_PORT}"
echo "  CORS:       ${CORS_ORIGIN}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -rp "Proceed with deployment? [y/N] " CONFIRM
if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]; then
  echo "Aborted."
  exit 0
fi

# ─── Step 1: Build frontend ──────────────────────

echo ""
echo "▶ Building frontend..."
cd "$PROJECT_DIR/web"
NEXT_PUBLIC_API_URL="${SITE_URL}" npm run build
echo "  ✓ Frontend built → web/out/"

# ─── Step 2: Build server ────────────────────────

echo ""
echo "▶ Building server..."
cd "$PROJECT_DIR/server"
npm run build
echo "  ✓ Server built → server/dist/"

# ─── Step 3: Generate production .env ─────────────

echo ""
echo "▶ Generating production .env..."
ENV_FILE="$PROJECT_DIR/server/.env.production"
cat > "$ENV_FILE" <<ENVEOF
PORT=${NODE_PORT}
DATABASE_PATH=./data/openkick.db
JWT_SECRET=${JWT_SECRET}
CORS_ORIGIN=${CORS_ORIGIN}
STATIC_DIR=${REMOTE_PATH}
ENVEOF

if [[ -n "$WAHA_URL" ]]; then
  cat >> "$ENV_FILE" <<ENVEOF
WAHA_URL=${WAHA_URL}
WAHA_PORT=${WAHA_PORT}
WEBHOOK_URL=${WEBHOOK_URL}
ENVEOF
fi

if [[ -n "$OPENAI_API_KEY" ]]; then
  echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> "$ENV_FILE"
fi

if [[ -n "$SMTP_HOST" ]]; then
  cat >> "$ENV_FILE" <<ENVEOF
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
ENVEOF
fi

echo "  ✓ .env.production created"

# ─── Step 4: Create .htaccess for routing ─────────

echo ""
echo "▶ Generating .htaccess..."
HTACCESS_FILE="$PROJECT_DIR/web/out/.htaccess"
cat > "$HTACCESS_FILE" <<'HTEOF'
# OpenKick — Apache config for cyon.ch
# Proxy API requests to the Node.js backend
RewriteEngine On

# Proxy /api/* requests to the Node.js server
RewriteCond %{REQUEST_URI} ^/api/ [NC]
RewriteRule ^api/(.*)$ http://127.0.0.1:NODEPORT/api/$1 [P,L]

# Proxy /.well-known/*, /llms.txt, /robots.txt, /mcp to the Node.js server
RewriteRule ^\.well-known/(.*)$ http://127.0.0.1:NODEPORT/.well-known/$1 [P,L]
RewriteRule ^llms\.txt$ http://127.0.0.1:NODEPORT/llms.txt [P,L]
RewriteRule ^robots\.txt$ http://127.0.0.1:NODEPORT/robots.txt [P,L]
RewriteRule ^mcp(.*)$ http://127.0.0.1:NODEPORT/mcp$1 [P,L]
RewriteRule ^uploads/(.*)$ http://127.0.0.1:NODEPORT/uploads/$1 [P,L]

# Proxy homepage to Node.js for server-side settings injection (OG tags, title, etc.)
RewriteRule ^$ http://127.0.0.1:NODEPORT/ [P,L]
RewriteRule ^index\.html$ http://127.0.0.1:NODEPORT/index.html [P,L]

# SPA fallback: serve index.html for non-file routes
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]

# Security headers
<IfModule mod_headers.c>
  Header set X-Content-Type-Options "nosniff"
  Header set X-Frame-Options "SAMEORIGIN"
  Header set X-XSS-Protection "1; mode=block"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>

# Caching for static assets
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType text/css "access plus 1 year"
  ExpiresByType application/javascript "access plus 1 year"
  ExpiresByType image/png "access plus 1 year"
  ExpiresByType image/svg+xml "access plus 1 year"
  ExpiresByType font/woff2 "access plus 1 year"
</IfModule>
HTEOF

# Replace placeholder with actual port
sed -i '' "s/NODEPORT/${NODE_PORT}/g" "$HTACCESS_FILE"
echo "  ✓ .htaccess created with API proxy → port ${NODE_PORT}"

# ─── Step 5: Create Node.js startup script ────────

echo ""
echo "▶ Generating server startup script..."
STARTUP_FILE="$PROJECT_DIR/server/start.sh"
cat > "$STARTUP_FILE" <<STARTEOF
#!/usr/bin/env bash
# OpenKick server — production startup
cd "\$(dirname "\$0")"

# Load production env
export \$(grep -v '^#' .env.production | xargs)

# Ensure data directory exists
mkdir -p data

# Start Node.js server
exec node dist/index.js
STARTEOF
chmod +x "$STARTUP_FILE"
echo "  ✓ start.sh created"

# ─── Step 6: Deploy via rsync ─────────────────────

echo ""
echo "▶ Deploying frontend to ${SSH_HOST}:${REMOTE_PATH}/ ..."
rsync -avz --delete \
  --exclude='.DS_Store' \
  "$PROJECT_DIR/web/out/" \
  "${SSH_USER}@${SSH_HOST}:${REMOTE_PATH}/"
echo "  ✓ Frontend deployed"

echo ""
echo "▶ Deploying server to ${SSH_HOST}:${REMOTE_PATH}/../openkick-server/ ..."
SERVER_REMOTE="${REMOTE_PATH}/../openkick-server"
ssh "${SSH_USER}@${SSH_HOST}" "mkdir -p ${SERVER_REMOTE}/data"

rsync -avz --delete \
  --exclude='node_modules' \
  --exclude='src' \
  --exclude='.env' \
  --exclude='.env.example' \
  --exclude='data/*.db' \
  "$PROJECT_DIR/server/dist/" \
  "${SSH_USER}@${SSH_HOST}:${SERVER_REMOTE}/dist/"

rsync -avz \
  "$PROJECT_DIR/server/package.json" \
  "$PROJECT_DIR/server/package-lock.json" \
  "$PROJECT_DIR/server/start.sh" \
  "$ENV_FILE" \
  "${SSH_USER}@${SSH_HOST}:${SERVER_REMOTE}/"
echo "  ✓ Server deployed"

# ─── Step 7: Install deps & start on remote ───────

echo ""
echo "▶ Installing production dependencies on remote..."
ssh "${SSH_USER}@${SSH_HOST}" "cd ${SERVER_REMOTE} && npm install --omit=dev"
echo "  ✓ Dependencies installed"

echo ""
echo "▶ Starting server on remote..."
ssh "${SSH_USER}@${SSH_HOST}" "cd ${SERVER_REMOTE} && chmod +x start.sh && nohup ./start.sh > server.log 2>&1 &"
echo "  ✓ Server started on port ${NODE_PORT}"

# ─── Cleanup ──────────────────────────────────────

rm -f "$ENV_FILE"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║   Deployment complete!                        ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "  Frontend: ${SITE_URL}"
echo "  API:      ${SITE_URL}/api/health"
echo ""
echo "  To check server logs:"
echo "    ssh ${SSH_USER}@${SSH_HOST} 'tail -f ${SERVER_REMOTE}/server.log'"
echo ""
echo "  To restart the server:"
echo "    ssh ${SSH_USER}@${SSH_HOST} 'cd ${SERVER_REMOTE} && pkill -f \"node dist/index.js\" ; nohup ./start.sh > server.log 2>&1 &'"
echo ""
